# Generated by Django 2.1.5 on 2019-01-19 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceOrder',
        ),
    ]
